In [222]:
import mysql.connector
import pandas as pd
import numpy as np

config = {
    'host': '212.227.90.6',
    'user': 'Equipo28',
    'password': 'E1q2u3i4p5o28',
    'database': 'Equip_28'
}

conn = mysql.connector.connect(**config)
cursor = conn.cursor()

cursor.execute("SELECT database();")
db_actual = cursor.fetchone()[0]
print(f"--- Conectado a la base de datos: {db_actual} ---")

cursor.execute("SHOW TABLES;")
tablas = cursor.fetchall()

print("Tablas encontradas:")
for t in tablas:
    print(f" -> {t[0]}")
    globals()[t[0]] = pd.read_sql("SELECT * FROM " + t[0], conn)
    
cursor.close()
conn.close()

--- Conectado a la base de datos: Equip_28 ---
Tablas encontradas:
 -> RRHH
 -> RRHH_27042026


C:\Users\anacl\AppData\Local\Temp\ipykernel_37088\210026830.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  globals()[t[0]] = pd.read_sql("SELECT * FROM " + t[0], conn)


 -> vista_duplicados_exactos
 -> vista_duplicados_exactos2


In [223]:
RRHH_27042026.info()


<class 'pandas.DataFrame'>
RangeIndex: 845 entries, 0 to 844
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       845 non-null    int64
 1   Reason_absence           845 non-null    int64
 2   Month_absence            845 non-null    int64
 3   Day_week                 845 non-null    int64
 4   Seasons                  845 non-null    int64
 5   Transportation_expense   845 non-null    int64
 6   Distance_Residence_Work  845 non-null    int64
 7   Service_time             845 non-null    int64
 8   Age                      845 non-null    int64
 9   Work_load_Average_day    845 non-null    str  
 10  Hit_target               845 non-null    int64
 11  Disciplinary_failure     845 non-null    str  
 12  Education                845 non-null    str  
 13  Son                      845 non-null    str  
 14  Social_drinker           845 non-null    str  
 15  Social_smoker    

DATA CLEANING

In [224]:
df = RRHH_27042026.copy()

In [225]:
# verifica duplicados
df[df.duplicated()]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
92,10,22,12,4,4,361,52,3,28,"261,306",...,0,1,1,1,0,4,80,172,27,8
348,34,23,10,3,4,118,10,10,37,"253,465",...,0,1,0,0,0,0,83,172,28,3
383,3,27,2,4,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
386,3,27,2,4,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
387,3,27,2,6,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
388,3,27,2,4,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
389,3,27,2,6,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
396,22,23,5,4,3,179,26,9,30,"246,074",...,0,3,0,0,0,0,56,171,19,3
412,28,23,12,4,4,225,26,9,28,"280,549",...,0,1,1,0,0,2,69,169,24,3
431,3,27,3,5,2,179,51,18,38,"222,196",...,0,1,0,1,0,0,89,170,31,3


In [226]:
#borra duplicados
df = df.drop_duplicates()

VALORES FALTANTES

In [227]:
df.isnull().values.any()

np.False_

### Check de valores unicos por cada columna

In [228]:
for col in df.columns:
    print(f"\nColonna: {col}")
    print(df[col].unique())


Colonna: ID
[ 14  36   9  28  11  13  34  22  26  20  10  15  17  24   3  18   7   1
  30   5   6   2  31  27  33  23  21  25  12  32  16  29  19   8   4  35
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107 108
 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125 126
 127 128 129 130 131 132 133 134 135 136]

Colonna: Reason_absence
[11 13  6  9 12 19 18  1 10 14  7 28  2 26 23 22 21 24 17  8  5 15  4 25
  3 27 16  0]

Colonna: Month_absence
[11  4  7  3  6 12 10  5  8  9  1  2  0]

Colonna: Day_week
[2 4 3 6 5]

Colonna: Seasons
[4 3 1 2]

Colonna: Transportation_expense
[155 118 228 225 289 369 179 300 260 361 291 246 330 279 235 157 189 388
 184 248 378 268 233 231]

Colonna: Distance_Residence_Work
[12 13 14 26 36 17 10 50 52 31 2

In [229]:
df[df['Month_absence'] == 0]


,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
737,4,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,"271,219",...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,"271,219",...,0,1,1,0,0,1,77,175,25,0
777,74,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0


In [230]:

df[df['Absenteeism_hours'] == 0]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
696,36,0,7,3,1,118,13,18,50,"239,554",...,1,1,1,1,0,0,98,178,31,0
697,20,0,9,2,4,260,50,11,36,"241,476",...,1,1,4,1,0,0,65,168,23,0
698,29,0,9,2,4,225,26,9,28,"241,476",...,1,1,1,0,0,2,69,169,24,0
699,11,0,9,3,4,289,36,13,33,"241,476",...,1,1,2,1,0,1,90,172,30,0
700,36,0,9,3,4,118,13,18,50,"241,476",...,1,1,1,1,0,0,98,178,31,0
701,13,0,9,4,4,369,17,12,31,"241,476",...,1,1,3,1,0,0,70,169,25,0
702,36,0,10,4,4,118,13,18,50,"253,465",...,1,1,1,1,0,0,98,178,31,0
703,34,27,1,2,2,118,10,10,37,"308,593",...,0,1,0,0,0,0,83,172,28,0
704,2,0,4,2,3,235,29,12,48,"326,452",...,1,1,1,0,1,5,88,163,33,0
705,7,0,5,4,3,279,5,14,39,"378,884",...,1,1,2,1,1,0,68,168,24,0


Check strings vacias por columnas

In [231]:
for col in df.columns:
    empty_mask = df[col].astype(str).str.strip() == ""
    if empty_mask.any():
        print(f"\nColuna: {col}")
        print(df[empty_mask])


Contar strings vacias por columna

In [232]:
for col in df.columns:
    count_empty = (df[col].astype(str).str.strip() == "").sum()
    if count_empty > 0:
        print(f"{col}: {count_empty} strings vacias")
    
if count_empty == 0:
    print("no se ha encontrado columnas con strings vacias")

no se ha encontrado columnas con strings vacias


Check strings extrañas (espacios, commas sueltas, etc)

In [233]:
for col in df.columns:
    suspicious = df[col].astype(str).str.contains(r"^\s+$")
    if suspicious.any():
        print(f"\nValores extraños en la columna {col}:")
        print(df[suspicious])

1 - Primero creo el mapeo para la conversion.  
2 - Creo una nueva columna 'Diseas_flag' segun el CID (Code International Diseases) para distinguir entre enfermedad y no enfermedad.  
3 - Finalmente convierto las enfermedad en string con el correspondiente.

In [234]:
reason_map = {
    1: "Infecciosas y Parasitarias",
    2: "Neoplasias",
    3: "Sangre e Inmunidad",
    4: "Endocrinas y Metabólicas",
    5: "Transtornos Mentales",
    6: "Sistema Nervioso",
    7: "Oftalmología (Ojo)",
    8: "Otología (Oído)",
    9: "Sistema Circulatorio",
    10: "Sistema Respiratorio",
    11: "Sistema Digestivo",
    12: "Piel y Tejido Subcutáneo",
    13: "Sistema Osteomuscular",
    14: "Sistema Genitourinario",
    15: "Embarazo, Parto y Puerperio",
    16: "Periodo Perinatal",
    17: "Anomalias Congénitas",
    18: "Síntomas y Hallazgos Clínicos",
    19: "Lesiones y Envenenamientos",
    20: "Causas externas",
    21: "Factores de Salud",
    22: "Seguimiento del Paciente",
    23: "Consulta Médica",
    24: "Donación de Sangre",
    25: "Examen de Laboratorio",
    26: "Falta injustificada",
    27: "Fisioterapia",
    28: "Consulta Dental"
}

In [235]:
df["Disease_flag"] = df["Reason_absence"].apply(
    lambda x: np.nan if x == 0 else ("Enfermedad" if x <= 21 else "No Enfermedad")
)


In [236]:
df["Reason_absence_mapped"] = df["Reason_absence"].map(reason_map)

In [237]:
df[df["Reason_absence_mapped"].isnull()]

""" dejo los valore  NaN en la columna 'Reason_absence_mapped' para los casos que no tienen un mapeo definido,
ya que esto me permite identificar fácilmente los casos de ausencia. De esta manera, puedo mantener la integridad de los datos. """

" dejo los valore  NaN en la columna 'Reason_absence_mapped' para los casos que no tienen un mapeo definido,\nya que esto me permite identificar fácilmente los casos de ausencia. De esta manera, puedo mantener la integridad de los datos. "

In [238]:
df['Month_absence'] = df['Month_absence'].replace(0, pd.NA)

In [239]:
month_map = {
    1: "Enero",
    2: "Febrero",
    3: "Marzo",
    4: "Abril",
    5: "Mayo",
    6: "Junio",
    7: "Julio",
    8: "Agosto",
    9: "Septiembre",
    10: "Octubre",
    11: "Noviembre",
    12: "Diciembre"
}
df['Month_absence_mapped'] = df['Month_absence'].map(month_map)

In [240]:
df.info()

<class 'pandas.DataFrame'>
Index: 806 entries, 0 to 839
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   ID                       806 non-null    int64 
 1   Reason_absence           806 non-null    int64 
 2   Month_absence            802 non-null    object
 3   Day_week                 806 non-null    int64 
 4   Seasons                  806 non-null    int64 
 5   Transportation_expense   806 non-null    int64 
 6   Distance_Residence_Work  806 non-null    int64 
 7   Service_time             806 non-null    int64 
 8   Age                      806 non-null    int64 
 9   Work_load_Average_day    806 non-null    str   
 10  Hit_target               806 non-null    int64 
 11  Disciplinary_failure     806 non-null    str   
 12  Education                806 non-null    str   
 13  Son                      806 non-null    str   
 14  Social_drinker           806 non-null    str   
 15  Socia

In [241]:
season_map = {
    1: "Verano",
    2: "Otoño",
    3: "Invierno",
    4: "Primavera"
}

df["Seasons"] = df["Seasons"].map(season_map)


In [242]:
df.info()

<class 'pandas.DataFrame'>
Index: 806 entries, 0 to 839
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   ID                       806 non-null    int64 
 1   Reason_absence           806 non-null    int64 
 2   Month_absence            802 non-null    object
 3   Day_week                 806 non-null    int64 
 4   Seasons                  806 non-null    str   
 5   Transportation_expense   806 non-null    int64 
 6   Distance_Residence_Work  806 non-null    int64 
 7   Service_time             806 non-null    int64 
 8   Age                      806 non-null    int64 
 9   Work_load_Average_day    806 non-null    str   
 10  Hit_target               806 non-null    int64 
 11  Disciplinary_failure     806 non-null    str   
 12  Education                806 non-null    str   
 13  Son                      806 non-null    str   
 14  Social_drinker           806 non-null    str   
 15  Socia

In [243]:
df['Seasons'].unique()

<StringArray>
['Primavera', 'Invierno', 'Verano', 'Otoño']
Length: 4, dtype: str

In [244]:
df['Day_week'].unique()

array([2, 4, 3, 6, 5])

In [245]:
day_map = {
    2: "Lunes",
    3: "Martes",
    4: "Miercoles",
    5: "Jueves",
    6: "Viernes"
}

df["Day_week"] = df["Day_week"].map(day_map)


In [246]:
df.info()

<class 'pandas.DataFrame'>
Index: 806 entries, 0 to 839
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   ID                       806 non-null    int64 
 1   Reason_absence           806 non-null    int64 
 2   Month_absence            802 non-null    object
 3   Day_week                 806 non-null    str   
 4   Seasons                  806 non-null    str   
 5   Transportation_expense   806 non-null    int64 
 6   Distance_Residence_Work  806 non-null    int64 
 7   Service_time             806 non-null    int64 
 8   Age                      806 non-null    int64 
 9   Work_load_Average_day    806 non-null    str   
 10  Hit_target               806 non-null    int64 
 11  Disciplinary_failure     806 non-null    str   
 12  Education                806 non-null    str   
 13  Son                      806 non-null    str   
 14  Social_drinker           806 non-null    str   
 15  Socia

In [247]:
df['Education'].unique()

<StringArray>
['1', '3', '2', '4']
Length: 4, dtype: str

In [248]:
df['Education']= df['Education'].astype(int)

In [249]:
education_map = {
    1: "Bachillerato",
    2: "Grado ",
    3: "Posgrado",
    4: "Máster"
}

df["Education_mapped"] = df["Education"].map(education_map)

In [250]:
df['Education_mapped']

0      Bachillerato
1      Bachillerato
2      Bachillerato
3      Bachillerato
4      Bachillerato
           ...     
835    Bachillerato
836        Posgrado
837    Bachillerato
838    Bachillerato
839    Bachillerato
Name: Education_mapped, Length: 806, dtype: str

Primero quito la coma y despues casteo la columna 'Work_load_Average_day' a float

In [251]:
df["Work_load_Average_day"] = df["Work_load_Average_day"].str.replace(",", ".").astype(float)


In [252]:
df.info()

<class 'pandas.DataFrame'>
Index: 806 entries, 0 to 839
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       806 non-null    int64  
 1   Reason_absence           806 non-null    int64  
 2   Month_absence            802 non-null    object 
 3   Day_week                 806 non-null    str    
 4   Seasons                  806 non-null    str    
 5   Transportation_expense   806 non-null    int64  
 6   Distance_Residence_Work  806 non-null    int64  
 7   Service_time             806 non-null    int64  
 8   Age                      806 non-null    int64  
 9   Work_load_Average_day    806 non-null    float64
 10  Hit_target               806 non-null    int64  
 11  Disciplinary_failure     806 non-null    str    
 12  Education                806 non-null    int64  
 13  Son                      806 non-null    str    
 14  Social_drinker           806 non-null    s

In [253]:
df['Work_load_Average_day'].unique()

array([284.031, 239.409, 264.604, 230.29 , 222.196, 377.55 , 280.549,
       261.306, 265.017, 237.656, 326.452, 239.554, 205.917, 306.345,
       343.253, 294.217, 253.957, 241.476, 275.312, 330.061, 378.884,
       251.818, 268.519, 313.532, 246.288, 275.089, 253.465, 244.387,
       246.074, 249.797, 308.593, 302.585, 265.615, 236.629, 261.756,
       284.853, 264.249, 271.219])

Converter columnas binarias para int

In [254]:
cols_binarias = ['Disciplinary_failure', 'Social_drinker', 'Social_smoker', 'Son', 'Pet']
for col in cols_binarias:
    df[col] = df[col].astype(int)

Estadística descriptiva

In [255]:
df.describe()


,ID,Reason_absence,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,Hit_target,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
count,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000,806.000000
mean,26.667494,18.866005,222.765509,29.186104,12.509926,36.527295,272.002268,94.588089,0.054591,1.297767,1.060794,0.568238,0.070720,0.749380,79.064516,172.241935,26.647643,7.500000
std,26.754204,8.505280,67.392599,14.673510,4.346973,6.658941,39.119518,3.772942,0.227320,0.682101,1.113453,0.495629,0.256515,1.312801,12.866087,6.154917,4.249944,14.669421
min,1.000000,0.000000,118.000000,5.000000,1.000000,27.000000,205.917000,81.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,56.000000,163.000000,19.000000,0.000000
25%,11.000000,13.000000,179.000000,16.000000,9.000000,31.000000,244.387000,92.250000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,69.000000,169.000000,24.000000,2.000000
50%,21.000000,23.000000,225.000000,26.000000,13.000000,37.000000,264.604000,95.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,80.000000,170.500000,25.000000,3.000000
75%,33.000000,26.000000,260.000000,49.000000,16.000000,40.000000,284.853000,97.000000,0.000000,1.000000,2.000000,1.000000,0.000000,1.000000,89.000000,172.000000,31.000000,8.000000
max,136.000000,28.000000,388.000000,52.000000,29.000000,58.000000,378.884000,100.000000,1.000000,4.000000,4.000000,1.000000,1.000000,8.000000,108.000000,196.000000,38.000000,120.000000


In [256]:
df.info()

<class 'pandas.DataFrame'>
Index: 806 entries, 0 to 839
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       806 non-null    int64  
 1   Reason_absence           806 non-null    int64  
 2   Month_absence            802 non-null    object 
 3   Day_week                 806 non-null    str    
 4   Seasons                  806 non-null    str    
 5   Transportation_expense   806 non-null    int64  
 6   Distance_Residence_Work  806 non-null    int64  
 7   Service_time             806 non-null    int64  
 8   Age                      806 non-null    int64  
 9   Work_load_Average_day    806 non-null    float64
 10  Hit_target               806 non-null    int64  
 11  Disciplinary_failure     806 non-null    int64  
 12  Education                806 non-null    int64  
 13  Son                      806 non-null    int64  
 14  Social_drinker           806 non-null    i

Renombrar nombre de columnas de ingles a castellano

In [258]:
# Dicionário de mapeo de columnas
mapeamento_es = {
    "ID": "id",
    "Reason_absence": "motivo_ausencia",
    "Month_absence": "mes_ausencia",
    "Day_week": "dia_semana",
    "Seasons": "estaciones",
    "Transportation_expense": "gasto_transporte",
    "Distance_Residence_Work": "distancia_casa_trabajo",
    "Service_time": "tiempo_servicio",
    "Age": "edad",
    "Work_load_Average_day": "carga_trabajo_diaria",
    "Hit_target": "cumplimiento_objetivo",
    "Disciplinary_failure": "falta_disciplinaria",
    "Education": "educacion",
    "Son": "hijos",
    "Social_drinker": "bebedor_social",
    "Social_smoker": "fumador_social",
    "Pet": "mascota",
    "Weight": "peso",
    "Height": "estatura",
    "Body_mass_index": "indice_masa_corporal",
    "Absenteeism_hours": "horas_ausentismo",
    "Disease_flag": "indicador_enfermedad",
    "Reason_absence_mapped": "motivo_ausencia_mapeado",
    "Month_absence_mapped": "mes_ausencia_mapeado",
    "Education_mapped": "educacion_mapeada"
}

# Renombrar en el dataset
df = df.rename(columns=mapeamento_es)


In [259]:
df.info()

<class 'pandas.DataFrame'>
Index: 806 entries, 0 to 839
Data columns (total 25 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       806 non-null    int64  
 1   motivo_ausencia          806 non-null    int64  
 2   mes_ausencia             802 non-null    object 
 3   dia_semana               806 non-null    str    
 4   estaciones               806 non-null    str    
 5   gasto_transporte         806 non-null    int64  
 6   distancia_casa_trabajo   806 non-null    int64  
 7   tiempo_servicio          806 non-null    int64  
 8   edad                     806 non-null    int64  
 9   carga_trabajo_diaria     806 non-null    float64
 10  cumplimiento_objetivo    806 non-null    int64  
 11  falta_disciplinaria      806 non-null    int64  
 12  educacion                806 non-null    int64  
 13  hijos                    806 non-null    int64  
 14  bebedor_social           806 non-null    i

In [ ]:
# df.to_csv("data_cleaning_2026_27_04.csv", index=False, encoding="utf-8")