In [72]:
import mysql.connector
import pandas as pd
import numpy as np

config = {
    'host': '212.227.90.6',
    'user': 'Equipo28',
    'password': 'E1q2u3i4p5o28',
    'database': 'Equip_28'
}

conn = mysql.connector.connect(**config)
cursor = conn.cursor()

cursor.execute("SELECT database();")
db_actual = cursor.fetchone()[0]
print(f"--- Conectado a la base de datos: {db_actual} ---")

cursor.execute("SHOW TABLES;")
tablas = cursor.fetchall()

print("Tablas encontradas:")
for t in tablas:
    print(f" -> {t[0]}")
    globals()[t[0]] = pd.read_sql("SELECT * FROM " + t[0], conn)
    
cursor.close()
conn.close()

--- Conectado a la base de datos: Equip_28 ---
Tablas encontradas:
 -> RRHH
 -> vista_duplicados_exactos


C:\Users\anacl\AppData\Local\Temp\ipykernel_29872\210026830.py:25: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  globals()[t[0]] = pd.read_sql("SELECT * FROM " + t[0], conn)


In [73]:
RRHH.info()

<class 'pandas.DataFrame'>
RangeIndex: 740 entries, 0 to 739
Data columns (total 21 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   ID                       740 non-null    int64
 1   Reason_absence           740 non-null    int64
 2   Month_absence            740 non-null    int64
 3   Day_week                 740 non-null    int64
 4   Seasons                  740 non-null    int64
 5   Transportation_expense   740 non-null    int64
 6   Distance_Residence_Work  740 non-null    int64
 7   Service_time             740 non-null    int64
 8   Age                      740 non-null    int64
 9   Work_load_Average_day    740 non-null    str  
 10  Hit_target               740 non-null    int64
 11  Disciplinary_failure     740 non-null    str  
 12  Education                740 non-null    str  
 13  Son                      740 non-null    str  
 14  Social_drinker           740 non-null    str  
 15  Social_smoker    

DATA CLEANING

In [74]:
df = RRHH.copy()

In [75]:
df[df.duplicated()]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
92,10,22,12,4,4,361,52,3,28,"261,306",...,0,1,1,1,0,4,80,172,27,8
348,34,23,10,3,4,118,10,10,37,"253,465",...,0,1,0,0,0,0,83,172,28,3
383,3,27,2,4,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
386,3,27,2,4,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
387,3,27,2,6,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
388,3,27,2,4,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
389,3,27,2,6,2,179,51,18,38,"251,818",...,0,1,0,1,0,0,89,170,31,3
396,22,23,5,4,3,179,26,9,30,"246,074",...,0,3,0,0,0,0,56,171,19,3
412,28,23,12,4,4,225,26,9,28,"280,549",...,0,1,1,0,0,2,69,169,24,3
431,3,27,3,5,2,179,51,18,38,"222,196",...,0,1,0,1,0,0,89,170,31,3


In [76]:
df = df.drop_duplicates()

VALORES FALTANTES

In [77]:
df.isnull().values.any()

np.False_

### Check de valores unicos por cada columna

In [78]:
for col in df.columns:
    print(f"\nColonna: {col}")
    print(df[col].unique())




Colonna: ID
[14 36  9 28 11 13 34 22 26 20 10 15 17 24  3 18  7  1 30  5  6  2 31 27
 33 23 21 25 12 32 16 29 19  8  4 35]

Colonna: Reason_absence
[11 13  6  9 12 19 18  1 10 14  7 28  2 26 23 22 21 24 17  8  5 15  4 25
  3 27 16  0]

Colonna: Month_absence
[11  4  7  3  6 12 10  5  8  9  1  2  0]

Colonna: Day_week
[2 4 3 6 5]

Colonna: Seasons
[4 3 1 2]

Colonna: Transportation_expense
[155 118 228 225 289 369 179 300 260 361 291 246 330 279 235 157 189 388
 184 248 378 268 233 231]

Colonna: Distance_Residence_Work
[12 13 14 26 36 17 10 50 52 31 22 25 51 16  5 11 27 20 29 15 42 49 48 35
 45]

Colonna: Service_time
[14 18 16  9 13 12 10 11  3 17  4  6  7  8  1 29 24 15]

Colonna: Age
[34 50 58 28 33 31 37 30 43 36 40 41 38 39 29 48 27 47 32 49 46 53]

Colonna: Work_load_Average_day
<StringArray>
['284,031', '239,409', '264,604', '230,290', '222,196', '377,550', '280,549',
 '261,306', '265,017', '237,656', '326,452', '239,554', '205,917', '306,345',
 '343,253', '294,217', '253,957',

In [79]:
df[df['Month_absence'] == 0]

# df[df['Absenteeism_hours'] == 0]

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Disciplinary_failure,Education,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
737,4,0,0,3,1,118,14,13,40,"271,219",...,0,1,1,1,0,8,98,170,34,0
738,8,0,0,4,2,231,35,14,39,"271,219",...,0,1,2,1,0,2,100,170,35,0
739,35,0,0,6,3,179,45,14,53,"271,219",...,0,1,1,0,0,1,77,175,25,0


Check strings vacias por columnas

In [80]:
for col in df.columns:
    empty_mask = df[col].astype(str).str.strip() == ""
    if empty_mask.any():
        print(f"\nColuna: {col}")
        print(df[empty_mask])

Contar strings vacias por columna

In [81]:
for col in df.columns:
    count_empty = (df[col].astype(str).str.strip() == "").sum()
    if count_empty > 0:
        print(f"{col}: {count_empty} strings vacias")
    
if count_empty == 0:
    print("no se ha encontrado columnas con strings vacias")

no se ha encontrado columnas con strings vacias


Check strings extrañas (espacios, commas sueltas, etc)

In [82]:
for col in df.columns:
    suspicious = df[col].astype(str).str.contains(r"^\s+$")
    if suspicious.any():
        print(f"\nValores extraños en la columna {col}:")
        print(df[suspicious])


1 - Primero creo el mapeo para la conversion.  
2 - Creo una nueva columna 'Diseas_flag' segun el CID (Code International Diseases) para distinguir entre enfermedad y no enfermedad.  
3 - Finalmente convierto las enfermedad en string con el correspondiente.

In [83]:
reason_map = {
    1: "Certain infectious and parasitic diseases",
    2: "Neoplasms",
    3: "Diseases of the blood and blood-forming organs and immune mechanism disorders",
    4: "Endocrine, nutritional and metabolic diseases",
    5: "Mental and behavioural disorders",
    6: "Diseases of the nervous system",
    7: "Diseases of the eye and adnexa",
    8: "Diseases of the ear and mastoid process",
    9: "Diseases of the circulatory system",
    10: "Diseases of the respiratory system",
    11: "Diseases of the digestive system",
    12: "Diseases of the skin and subcutaneous tissue",
    13: "Diseases of the musculoskeletal system and connective tissue",
    14: "Diseases of the genitourinary system",
    15: "Pregnancy, childbirth and the puerperium",
    16: "Certain conditions originating in the perinatal period",
    17: "Congenital malformations, deformations and chromosomal abnormalities",
    18: "Symptoms, signs and abnormal clinical and laboratory findings, not elsewhere classified",
    19: "Injury, poisoning and other consequences of external causes",
    20: "External causes of morbidity and mortality",
    21: "Factors influencing health status and contact with health services",
    22: "Patient follow-up",
    23: "Medical consultation",
    24: "Blood donation",
    25: "Laboratory examination",
    26: "Unjustified absence",
    27: "Physiotherapy",
    28: "Dental consultation"
}


In [84]:
df["Disease_flag"] = df["Reason_absence"].apply(
    lambda x: np.nan if x == 0 else ("Disease" if x <= 21 else "Not disease")
)


In [85]:
df["Reason_absence_mapped"] = df["Reason_absence"].map(reason_map)

In [86]:
df[df["Reason_absence_mapped"].isnull()]

""" dejo los valore  NaN en la columna 'Reason_absence_mapped' para los casos que no tienen un mapeo definido,
ya que esto me permite identificar fácilmente los casos de ausencia. De esta manera, puedo mantener la integridad de los datos. """

" dejo los valore  NaN en la columna 'Reason_absence_mapped' para los casos que no tienen un mapeo definido,\nya que esto me permite identificar fácilmente los casos de ausencia. De esta manera, puedo mantener la integridad de los datos. "

In [87]:
df['Month_absence'] = df['Month_absence'].replace(0, pd.NA)

In [88]:
month_map = {
    1: "January",
    2: "February",
    3: "March",
    4: "April",
    5: "May",
    6: "June",
    7: "July",
    8: "August",
    9: "September",
    10: "October",
    11: "November",
    12: "December"
}
df['Month_absence_mapped'] = df['Month_absence'].map(month_map)

In [89]:
df.info()

<class 'pandas.DataFrame'>
Index: 706 entries, 0 to 739
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   ID                       706 non-null    int64 
 1   Reason_absence           706 non-null    int64 
 2   Month_absence            703 non-null    object
 3   Day_week                 706 non-null    int64 
 4   Seasons                  706 non-null    int64 
 5   Transportation_expense   706 non-null    int64 
 6   Distance_Residence_Work  706 non-null    int64 
 7   Service_time             706 non-null    int64 
 8   Age                      706 non-null    int64 
 9   Work_load_Average_day    706 non-null    str   
 10  Hit_target               706 non-null    int64 
 11  Disciplinary_failure     706 non-null    str   
 12  Education                706 non-null    str   
 13  Son                      706 non-null    str   
 14  Social_drinker           706 non-null    str   
 15  Socia

In [90]:
season_map = {
    1: "summer",
    2: "autumn",
    3: "winter",
    4: "spring"
}

df["Seasons"] = df["Seasons"].map(season_map)


In [91]:
df.info()

<class 'pandas.DataFrame'>
Index: 706 entries, 0 to 739
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   ID                       706 non-null    int64 
 1   Reason_absence           706 non-null    int64 
 2   Month_absence            703 non-null    object
 3   Day_week                 706 non-null    int64 
 4   Seasons                  706 non-null    str   
 5   Transportation_expense   706 non-null    int64 
 6   Distance_Residence_Work  706 non-null    int64 
 7   Service_time             706 non-null    int64 
 8   Age                      706 non-null    int64 
 9   Work_load_Average_day    706 non-null    str   
 10  Hit_target               706 non-null    int64 
 11  Disciplinary_failure     706 non-null    str   
 12  Education                706 non-null    str   
 13  Son                      706 non-null    str   
 14  Social_drinker           706 non-null    str   
 15  Socia

In [92]:
df['Seasons'].unique()

<StringArray>
['spring', 'winter', 'summer', 'autumn']
Length: 4, dtype: str

In [93]:
df['Day_week'].unique()

array([2, 4, 3, 6, 5])

In [ ]:
day_map = {
    2: "Monday",
    3: "Tuesday",
    4: "Wednesday",
    5: "Thursday",
    6: "Friday"
}

df["Day_week"] = df["Day_week"].map(day_map)


In [95]:
df.info()

<class 'pandas.DataFrame'>
Index: 706 entries, 0 to 739
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype 
---  ------                   --------------  ----- 
 0   ID                       706 non-null    int64 
 1   Reason_absence           706 non-null    int64 
 2   Month_absence            703 non-null    object
 3   Day_week                 706 non-null    str   
 4   Seasons                  706 non-null    str   
 5   Transportation_expense   706 non-null    int64 
 6   Distance_Residence_Work  706 non-null    int64 
 7   Service_time             706 non-null    int64 
 8   Age                      706 non-null    int64 
 9   Work_load_Average_day    706 non-null    str   
 10  Hit_target               706 non-null    int64 
 11  Disciplinary_failure     706 non-null    str   
 12  Education                706 non-null    str   
 13  Son                      706 non-null    str   
 14  Social_drinker           706 non-null    str   
 15  Socia

In [109]:
df['Education'].unique()

<StringArray>
['1', '3', '2', '4']
Length: 4, dtype: str

In [115]:
df['Education']= df['Education'].astype(int)

In [116]:
education_map = {
    1: "high_school",
    2: "graduate ",
    3: "postgraduate",
    4: "master_and_doctor"
}

df["Education_mapped"] = df["Education"].map(education_map)

In [117]:
df['Education_mapped']

0      high_school
1      high_school
2      high_school
3      high_school
4      high_school
          ...     
735    high_school
736      graduate 
737    high_school
738    high_school
739    high_school
Name: Education_mapped, Length: 706, dtype: str

Primero quito la coma y despues casteo la columna 'Work_load_Average_day' a float

In [96]:
df["Work_load_Average_day"] = df["Work_load_Average_day"].str.replace(",", "").astype(float)


In [97]:
df.info()

<class 'pandas.DataFrame'>
Index: 706 entries, 0 to 739
Data columns (total 24 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   ID                       706 non-null    int64  
 1   Reason_absence           706 non-null    int64  
 2   Month_absence            703 non-null    object 
 3   Day_week                 706 non-null    str    
 4   Seasons                  706 non-null    str    
 5   Transportation_expense   706 non-null    int64  
 6   Distance_Residence_Work  706 non-null    int64  
 7   Service_time             706 non-null    int64  
 8   Age                      706 non-null    int64  
 9   Work_load_Average_day    706 non-null    float64
 10  Hit_target               706 non-null    int64  
 11  Disciplinary_failure     706 non-null    str    
 12  Education                706 non-null    str    
 13  Son                      706 non-null    str    
 14  Social_drinker           706 non-null    s

In [98]:
df['Work_load_Average_day'].unique()

array([284031., 239409., 264604., 230290., 222196., 377550., 280549.,
       261306., 265017., 237656., 326452., 239554., 205917., 306345.,
       343253., 294217., 253957., 241476., 275312., 330061., 378884.,
       251818., 268519., 313532., 246288., 275089., 253465., 244387.,
       246074., 249797., 308593., 302585., 265615., 236629., 261756.,
       284853., 264249., 271219.])

Converter columnas binarias para int

In [99]:
cols_binarias = ['Disciplinary_failure', 'Social_drinker', 'Social_smoker', 'Son', 'Pet']
for col in cols_binarias:
    df[col] = df[col].astype(int)

Estadística descriptiva

In [107]:
df.describe()


,ID,Reason_absence,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,Hit_target,Disciplinary_failure,Son,Social_drinker,Social_smoker,Pet,Weight,Height,Body_mass_index,Absenteeism_hours
count,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000,706.000000
mean,18.192635,18.882436,222.977337,29.297450,12.495751,36.478754,272089.984419,94.548159,0.056657,1.060907,0.565156,0.076487,0.769122,79.005666,172.202550,26.635977,7.143059
std,10.927472,8.482877,67.293426,14.706661,4.370190,6.563404,39458.780251,3.803854,0.231350,1.104717,0.496088,0.265965,1.333351,12.862501,6.159814,4.254901,13.608120
min,1.000000,0.000000,118.000000,5.000000,1.000000,27.000000,205917.000000,81.000000,0.000000,0.000000,0.000000,0.000000,0.000000,56.000000,163.000000,19.000000,0.000000
25%,10.000000,13.000000,179.000000,16.000000,9.000000,31.000000,244387.000000,92.250000,0.000000,0.000000,0.000000,0.000000,0.000000,69.000000,169.000000,24.000000,2.000000
50%,18.000000,23.000000,225.000000,26.000000,13.000000,37.000000,264604.000000,95.000000,0.000000,1.000000,1.000000,0.000000,0.000000,80.000000,171.000000,25.000000,3.000000
75%,28.000000,26.000000,260.000000,49.000000,16.000000,40.000000,294217.000000,97.000000,0.000000,2.000000,1.000000,0.000000,1.000000,89.000000,172.000000,31.000000,8.000000
max,36.000000,28.000000,388.000000,52.000000,29.000000,58.000000,378884.000000,100.000000,1.000000,4.000000,1.000000,1.000000,8.000000,108.000000,196.000000,38.000000,120.000000


Detectar outliers (IQR)

In [106]:
numeric_df = df.select_dtypes(include=['int64', 'float64'])

Q1 = numeric_df.quantile(0.25)
Q3 = numeric_df.quantile(0.75)
IQR = Q3 - Q1

outliers = ((numeric_df < (Q1 - 1.5 * IQR)) | (numeric_df > (Q3 + 1.5 * IQR)))
outliers.sum()

ID                           0
Reason_absence               0
Transportation_expense       3
Distance_Residence_Work      0
Service_time                 5
Age                          8
Work_load_Average_day       32
Hit_target                  19
Disciplinary_failure        40
Son                          0
Social_drinker               0
Social_smoker               54
Pet                         45
Weight                       0
Height                     119
Body_mass_index              0
Absenteeism_hours           44
dtype: int64

In [119]:
df["has_outlier"] = outliers.any(axis=1)

In [122]:
df.describe(include="all")

,ID,Reason_absence,Month_absence,Day_week,Seasons,Transportation_expense,Distance_Residence_Work,Service_time,Age,Work_load_Average_day,...,Pet,Weight,Height,Body_mass_index,Absenteeism_hours,Disease_flag,Reason_absence_mapped,Month_absence_mapped,Education_mapped,has_outlier
count,706.000000,706.000000,703.0,706,706,706.000000,706.000000,706.000000,706.000000,706.000000,...,706.000000,706.000000,706.000000,706.000000,706.000000,663,663,703,706,706
unique,NaN,NaN,12.0,5,4,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,2,27,12,4,2
top,NaN,NaN,3.0,Monday,spring,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Not disease,Medical consultation,March,high_school,False
freq,NaN,NaN,83.0,158,189,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,401,142,83,582,435
mean,18.192635,18.882436,NaN,NaN,NaN,222.977337,29.297450,12.495751,36.478754,272089.984419,...,0.769122,79.005666,172.202550,26.635977,7.143059,NaN,NaN,NaN,NaN,NaN
std,10.927472,8.482877,NaN,NaN,NaN,67.293426,14.706661,4.370190,6.563404,39458.780251,...,1.333351,12.862501,6.159814,4.254901,13.608120,NaN,NaN,NaN,NaN,NaN
min,1.000000,0.000000,NaN,NaN,NaN,118.000000,5.000000,1.000000,27.000000,205917.000000,...,0.000000,56.000000,163.000000,19.000000,0.000000,NaN,NaN,NaN,NaN,NaN
25%,10.000000,13.000000,NaN,NaN,NaN,179.000000,16.000000,9.000000,31.000000,244387.000000,...,0.000000,69.000000,169.000000,24.000000,2.000000,NaN,NaN,NaN,NaN,NaN
50%,18.000000,23.000000,NaN,NaN,NaN,225.000000,26.000000,13.000000,37.000000,264604.000000,...,0.000000,80.000000,171.000000,25.000000,3.000000,NaN,NaN,NaN,NaN,NaN
75%,28.000000,26.000000,NaN,NaN,NaN,260.000000,49.000000,16.000000,40.000000,294217.000000,...,1.000000,89.000000,172.000000,31.000000,8.000000,NaN,NaN,NaN,NaN,NaN
